### ISSUE TITLE
Behind Proxy?

### ISSUE THREAD

**Issue by SteveScott** [competencytestlvl/webdriver_auto_update#15]
I am getting a 407 error behind my corporate proxy when I use this library. Where do I pass in the proxy settings?

**Comment by competencytestlvl** [comment]
@SteveScott, Thank you for reaching out. May I kindly know in which section of the code did you encounter this issue? Your issue seems to be due to authentication. For example, if you are attempting to obtain the latest chromedriver version endpoint using the requests module, you may define your proxy details and pass them as arguments:

```
    proxy = {
        'https': 'https://your_username:your_password@your_proxy_server:your_proxy_port'
    }
    requests.get(LAST_KNOWN_GOOD_VERSIONS_URL, proxies=proxy)
```

Hopefully this suggestion may assist you.

**Comment by SteveScott** [comment]
I am calling``` WebdriverAutoUpdate(CHROMEDRIVER_PATH)```
Digging into the code it appears to be using wget. WGet pulls proxy settings from the HTTP_PROXY and HTTPS_PROXY environment variables. So I am working with my IT team to add ```googlechromelabs.github.io``` to the allow list.

**Comment by SteveScott** [comment]
I have access. Just needed to allow it. You may close the ticket.
