### ISSUE TITLE
Chromedriver being installed is not up-to-date.

### ISSUE THREAD

**Issue by SteveScott** [competencytestlvl/webdriver_auto_update#16]
I am getting the following error:

```
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.160)
```
I read on StackOverflow this error occurs when the Chromedriver doesn't match Chrome. So I checked the version of webdriver and Chrome. The Chrome version listed in the error message is the version of my browser, 19.0.6045.160. I checked and saw that webdriver_auto_update did in fact overwrite the driver today, but the version of the driver installed is only  v118.0.5993.70, not 119 . I am concerned that webdriver_auto_update is not up to date for some reason.

I have no control over my Chrome updates at work. I am on Windows.

**Comment by SteveScott** [comment]
I'm sorry, the Chrome Driver was not being updated. The last update was 10/20. Hmm. I must be doing something wrong.

**Comment by competencytestlvl** [comment]
@SteveScott Automatic version updates by Chrome may be different than the stable release versions of ChromeDriver. For example, Chrome and ChromeDriver's patch versions may differ slightly such as below, but their major, minor and build numbers for compatibility are the same:

_Example as of 2023-11-24T22:08:52_
Chrome: 119.0.6045.160 
ChromeDriver (stable release): 119.0.6045.105

**Comment by SteveScott** [comment]
Thanks for the help. I have a new issue.
As I understand it webdriver_auto_update pulls the latest version of the ChromeDriver. This assumes that the version of Chrome is up-to-date. But what if my workplace holds-off on updating Chrome? Then my ChromeDriver will be ahead of the local installation of Chrome and breaks? I wonder if there is a way to look up the currently-installed version of Chrome, and pull the driver that matches it?

**Comment by competencytestlvl** [comment]
@SteveScott To answer your questions, I would separate it into two sections 

**1. Checking currently installed version of Chrome program.**

  - Installation of Chrome locally should have a dedicated directory with a version number as the directory name. In the example image below (Windows machine), there is a directory "120.0.6099.130" corresponding to the current locally installed version of Chrome: 
  
  ![image](https://github.com/competencytestlvl/webdriver_auto_update/assets/86846386/c2cef147-bba2-4990-a1d0-5dfd4cc40c47)

![image](https://github.com/competencytestlvl/webdriver_auto_update/assets/86846386/c75c6cfa-a3d7-4942-96d8-61931a49b34b)

  - As such, the local Chrome version number can be extracted via libraries such as **_os_** or _**pathlib**_
  - Since this a rather important feature, it could be included in the next release this project.

**2.  Pulling chromedriver that matches the locally installed Chrome version**
 - This can be performed simply by setting the attribute _online_driver_version_. The _download_url_ variable contains the string from _online_driver_version_.
![image](https://github.com/competencytestlvl/webdriver_auto_update/assets/86846386/6a24338f-96df-4da7-9a37-9f35934085e6)
 - As an example below using windows, when the _online_driver_version_ is set to 116.0.5793.0, the _download_url_ variable would be a complete link to download chromedriver of version 116.0.5793.0:  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5793.0/win64/chromedriver-win64.zip
 - Perhaps a setter or alternative function could be introduced in the next release of this project to allow the option of downloading a particular chromedriver version (e.g. version 116.0.5793.0) instead of the default latest stable release.

**Comment by SteveScott** [comment]
There is an example of how to check the Chrome version with and without the web driver here:

https://sqa.stackexchange.com/questions/41354/programmatically-determine-chrome-browser-version-regardless-of-os

**Comment by SteveScott** [comment]
I will submit a pull request shortly

**Comment by competencytestlvl** [comment]
@SteveScott Currently work in progress. However, I have created a feature branch with a possible implementation to solve the issue of "**Checking currently installed version of Google Chrome program**".

A new release should be expected soon with a new utility class called _**ChromeAppUtils**_. Meanwhile, here is the code snippet:

https://github.com/competencytestlvl/webdriver_auto_update/blob/feature/chrome-app-version-extraction/src/webdriver_auto_update/chrome_app_utils.py
